# Generated by Django 2.0.4 on 2018-05-12 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0003_auto_20180512_1757'),

    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='stocklist',
        ),
    ]
