# Generated by Django 2.0.4 on 2018-04-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
    ]
