# Generated by Django 2.0.4 on 2018-05-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0002_auto_20180427_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='person',
            name='log_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.TextField(default='0000'),
        ),
        migrations.AddField(
            model_name='person',
            name='stocklist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
