# Generated by Django 2.0.4 on 2018-05-31 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0004_remove_person_stocklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='money',
            field=models.IntegerField(blank=True, default='1000', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
