# Generated by Django 2.0.4 on 2018-05-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0006_auto_20180513_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='number_of_stocks_person_has',
            field=models.IntegerField(default=0),
        ),
    ]
