# Generated by Django 2.0.4 on 2018-05-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0007_auto_20180513_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='number_of_stocks_person_has',
            field=models.TextField(default=0),
        ),
    ]
