# Generated by Django 2.0.4 on 2018-05-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0008_auto_20180513_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='Bourse_fk',
            new_name='bourse',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='person_fk',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='membership',
            name='number_of_stocks_person_has',
            field=models.IntegerField(default=0),
        ),
    ]
