# Generated by Django 2.0.4 on 2018-05-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0009_auto_20180515_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='money',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
