# Generated by Django 2.0.4 on 2018-05-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0010_person_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='person_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
