# Generated by Django 2.0.4 on 2018-05-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0011_membership_person_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='person_name',
        ),
    ]
