# Generated by Django 2.0.4 on 2018-05-24 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0013_auto_20180524_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='bourse',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='person',
        ),
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
