# Generated by Django 2.0.4 on 2018-05-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0014_auto_20180524_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='money',
            field=models.IntegerField(blank=True, default='1000', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
