# Generated by Django 2.0.4 on 2018-07-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_education_ditails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='ditails',
            new_name='details',
        ),
    ]
