# Generated by Django 2.0.4 on 2018-05-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('title', models.TextField(primary_key=True, serialize=False)),
                ('date_day', models.IntegerField()),
                ('date_month', models.IntegerField()),
                ('date_year', models.IntegerField()),
                ('news_date', models.TextField()),
                ('news_Quote', models.TextField()),
                ('news_Body', models.TextField()),
            ],
        ),
    ]
