# Generated by Django 2.0.4 on 2018-05-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='bourse',
            field=models.ForeignKey(on_delete=True, related_name='fk_bourse', to='Bourseapp.Bourse'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=True, related_name='fk_person', to='Personapp.Person'),
        ),
    ]
