# Generated by Django 2.0.4 on 2018-05-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0002_auto_20180526_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='bourse',
            field=models.ForeignKey(on_delete=True, related_name='fk_boursessss', to='Bourseapp.Bourse'),
        ),
    ]
