# Generated by Django 2.0.4 on 2018-05-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0004_auto_20180526_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='person',
        ),
    ]
