# Generated by Django 2.0.4 on 2018-05-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personapp', '0015_auto_20180524_1916'),
        ('Membership', '0005_remove_membership_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(default='null', on_delete=True, related_name='fk_person', to='Personapp.Person'),
            preserve_default=False,
        ),
    ]
