# Generated by Django 2.0.4 on 2018-04-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bourseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bourse',
            name='EPS',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='PE',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='best_Demand',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='best_Supply',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='count_Of_Transaction',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='final_Amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='final_Change',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='final_Persentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='index_Percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='lastest_Amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='lastest_Change',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='lastest_Percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='market',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='max_V',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='min_V',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='stock_Market_Value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='yesterday',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
