# Generated by Django 2.0.4 on 2018-04-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bourseapp', '0003_auto_20180423_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bourse',
            name='id',
        ),
        migrations.AddField(
            model_name='bourse',
            name='namad',
            field=models.TextField(default='none', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='EPS',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='PE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='best_Demand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='best_Supply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='count_Of_Transaction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='final_Amount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='final_Change',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='final_Persentage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='index_Percentage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='lastest_Amount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='lastest_Change',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='lastest_Percentage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='max_V',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='min_V',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='stock_Market_Value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='volume',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='yesterday',
            field=models.TextField(blank=True, null=True),
        ),
    ]
