# Generated by Django 2.0.4 on 2018-04-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bourseapp', '0002_auto_20180421_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bourse',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True),
        ),
    ]
